sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t jay0764/docker-react -f Dockerfile.dev .

script:
  - docker run  -e CI=true jay0764/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-2-286135280194'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
